# Deployment postgre
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:15.0
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: kubenews
            - name: POSTGRES_PASSWORD
              value: Pg#123
            - name: POSTGRES_USER
              value: kubenews

---
# Service postgre
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
    - port: 5432

---
# Deployment kubenews
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
    spec:
      containers:
        - name: kubenews
          image: cruzmarcus/kube-news:v1
          ports:
            - containerPort: 8080
          env:
            - name: DB_DATABASE
              value: kubenews
            - name: DB_HOST
              value: postgre
            - name: DB_PASSWORD
              value: Pg#123
            - name: DB_USERNAME
              value: kubenews

---
# Service kubenews
apiVersion: v1
kind: Service
metadata:
  name: kubenews
spec:
  selector:
    app: kubenews
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort

