name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Docker Login
      uses: docker/login-action@v1.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        context: ./kube-news/src
        file: ./kube-news/src/Dockerfile
        push: true
        tags: |
          cruzmarcus/kube-news:v${{ github.run_number }}
          cruzmarcus/kube-news:latest
  
  CD:
    runs-on: ubuntu-latest
    needs: ["CI"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: "Configure AWS Credentials"
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
    - name: Setting the kubeconfig
      run: echo "setting the kubeconfig"
    - name: Apply the deploy
      run: echo "run kubectl apply"
    
